name: Build & Test

on:
  push:
    branches: ['*']
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Start container
        run: |
          docker run -d \
            --workdir /__w/Lean.DataSource.SDK/Lean.DataSource.SDK \
            -v /home/runner/work:/__w \
            --name test-container \
            quantconnect/lean:foundation \
            tail -f /dev/null

      - name: Build DataSource
        run: runInContainer dotnet build ./QuantConnect.DataSource.csproj /p:Configuration=Release /v:quiet /p:WarningLevel=1

      - name: Build Tests
        run: runInContainer dotnet build ./tests/Tests.csproj /p:Configuration=Release /v:quiet /p:WarningLevel=1

      - name: Run Tests
        run: runInContainer dotnet test ./tests/bin/Release/net10.0/Tests.dll

      - name: Stop container
        run: docker rm -f test-container

      - name: Run C# Demonstration Algorithm
        run: |
          cat > ../Lean.DataSource.SDK/demo-csharp-config.json << 'EOF'
          {
              "algorithm-type-name": "Demostration",
              "algorithm-language": "CSharp",
              "algorithm-location": "tests/bin/Release/net10.0/Tests.dll",
              "data-folder": "../Lean/Data/"
          }
          EOF
          runInContainer dotnet ../Lean/Launcher/bin/Release/net10.0/QuantConnect.Lean.Launcher.dll --config ./demo-csharp-config.json

      - name: Run Python Demonstration Algorithm
        run: |
          cat > ../Lean.DataSource.SDK/demo-python-config.json << 'EOF'
          {
              "algorithm-type-name": "Demostration",
              "algorithm-language": "Python",
              "algorithm-location": "Demostration.py",
              "data-folder": "../Lean/Data/"
          }
          EOF
          runInContainer dotnet ../Lean/Launcher/bin/Release/net10.0/QuantConnect.Lean.Launcher.dll --config ./demo-python-config.json

      - name: Run C# Demonstration Universe Algorithm
        run: |
          cat > ../Lean.DataSource.SDK/demo-csharp-config.json << 'EOF'
          {
              "algorithm-type-name": "DemostrationUniverse",
              "algorithm-language": "CSharp",
              "algorithm-location": "tests/bin/Release/net10.0/Tests.dll",
              "data-folder": "../Lean/Data/"
          }
          EOF
          runInContainer dotnet ../Lean/Launcher/bin/Release/net10.0/QuantConnect.Lean.Launcher.dll --config ./demo-csharp-config.json

      - name: Run Python Demonstration Universe Algorithm
        run: |
          cat > ../Lean.DataSource.SDK/demo-python-config.json << 'EOF'
          {
              "algorithm-type-name": "DemostrationUniverse",
              "algorithm-language": "Python",
              "algorithm-location": "DemostrationUniverse.py",
              "data-folder": "../Lean/Data/"
          }
          EOF
          runInContainer dotnet ../Lean/Launcher/bin/Release/net10.0/QuantConnect.Lean.Launcher.dll --config ./demo-python-config.json

