name: Rename & Test

on:
  workflow_call:

jobs:
  rename-build:
    if: github.repository == 'QuantConnect/Lean.DataSource.SDK'
    runs-on: self-hosted
    container:
        image: quantconnect/lean:foundation
        options: --cpus 12 --memory 12g
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup
        uses: ./.github/actions/setup

      - name: Rename Dataset
        run: |
          cp -r . ../Lean.DataSource.Rename
          cd ../Lean.DataSource.Rename
          python renameDataset.py Rename Dataset

      - name: Build Renamed DataSource
        run: cd ../Lean.DataSource.Rename && dotnet build ./QuantConnect.DataSource.csproj /p:Configuration=Release /v:quiet /p:WarningLevel=1

      - name: Build Renamed Tests
        run: cd ../Lean.DataSource.Rename && dotnet build ./tests/Tests.csproj /p:Configuration=Release /v:quiet /p:WarningLevel=1

      - name: Run Renamed Tests
        run: cd ../Lean.DataSource.Rename && dotnet test ./tests/bin/Release/net10.0/Tests.dll
