name: Rename & Test

on:
  workflow_call:

jobs:
  rename-build:
    if: github.repository == 'QuantConnect/Lean.DataSource.SDK'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup
        uses: ./.github/actions/setup

      - name: Rename Dataset
        run: |
          cp -r . ../Lean.DataSource.RenameDataset
          cd ../Lean.DataSource.RenameDataset
          python renameDataset.py Rename Dataset

      - name: Start container (renamed)
        run: |
          docker run -d \
            --workdir /__w/Lean.DataSource.SDK/Lean.DataSource.RenameDataset \
            -v /home/runner/work:/__w \
            --name test-container \
            quantconnect/lean:foundation \
            tail -f /dev/null

      - name: Build Renamed DataSource
        run: runInContainer dotnet build ./QuantConnect.DataSource.csproj /p:Configuration=Release /v:quiet /p:WarningLevel=1

      - name: Build Renamed Tests
        run: runInContainer dotnet build ./tests/Tests.csproj /p:Configuration=Release /v:quiet /p:WarningLevel=1

      - name: Run Renamed Tests
        run: runInContainer dotnet test ./tests/bin/Release/net10.0/Tests.dll
